/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum TypeAdditionalDataUpdateRequest {
    Boolean = "Boolean",
    String = "String",
    LessThanNilGreaterThan = "<nil>",
}

export class AdditionalDataUpdateRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "key" })
    key?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "required" })
    required?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: TypeAdditionalDataUpdateRequest;
}
