/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum CalculationTypeBulkCalculation1099ItemUpdate {
    Balances = "Balances",
    Submissions = "Submissions",
    LessThanNilGreaterThan = "<nil>",
}

export class BulkCalculation1099ItemUpdate extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "calculationType" })
    calculationType?: CalculationTypeBulkCalculation1099ItemUpdate;

    @SpeakeasyMetadata()
    @Expose({ name: "clientId" })
    clientId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "labels" })
    labels?: Record<string, string>;

    @SpeakeasyMetadata()
    @Expose({ name: "year" })
    year?: number;
}
