/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Address } from "./address";
import { C43d8e931fa2aa65f8160dad6cddeff3ae5f333e9b96d96dc85708e786c6a875 } from "./c43d8e931fa2aa65f8160dad6cddeff3ae5f333e9b96d96dc85708e786c6a875";
import { Expose, Type } from "class-transformer";

export enum StatusCardDetails {
    Active = "Active",
    Inactive = "Inactive",
    Stolen = "Stolen",
    Lost = "Lost",
    Frozen = "Frozen",
    ClosedByCustomer = "ClosedByCustomer",
    SuspectedFraud = "SuspectedFraud",
}

export enum TypeCardDetails {
    IndividualDebitCard = "individualDebitCard",
    BusinessDebitCard = "businessDebitCard",
    IndividualVirtualDebitCard = "individualVirtualDebitCard",
    BusinessVirtualDebitCard = "businessVirtualDebitCard",
}

export class CardDetails extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "address" })
    @Type(() => Address)
    address: Address;

    @SpeakeasyMetadata()
    @Expose({ name: "brand" })
    brand: string;

    @SpeakeasyMetadata()
    @Expose({ name: "createdAt" })
    createdAt: string;

    @SpeakeasyMetadata()
    @Expose({ name: "expirationDate" })
    expirationDate: string;

    @SpeakeasyMetadata()
    @Expose({ name: "internal" })
    @Type(() => C43d8e931fa2aa65f8160dad6cddeff3ae5f333e9b96d96dc85708e786c6a875)
    internal: C43d8e931fa2aa65f8160dad6cddeff3ae5f333e9b96d96dc85708e786c6a875;

    @SpeakeasyMetadata()
    @Expose({ name: "last4Digits" })
    last4Digits: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    @SpeakeasyMetadata()
    @Expose({ name: "pinSet" })
    pinSet?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: StatusCardDetails;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type: TypeCardDetails;
}
