/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum WorkflowStatusClientOptions {
    Pending = "Pending",
    PreApproved = "PreApproved",
    Approved = "Approved",
    PaymentInitiated = "PaymentInitiated",
    Funded = "Funded",
    Declined = "Declined",
}

export enum WorkflowSubStatusClientOptions {
    Submitted = "Submitted",
}

export class ClientOptions extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "comment" })
    comment?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "payDate" })
    payDate?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "workflowStatus" })
    workflowStatus?: WorkflowStatusClientOptions;

    @SpeakeasyMetadata()
    @Expose({ name: "workflowSubStatus" })
    workflowSubStatus?: WorkflowSubStatusClientOptions;
}
