/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { B9789f45f8c8070ff38a64d80c2e4a8732ddaf329e46546474400d26f84c0f1c } from "./b9789f45f8c8070ff38a64d80c2e4a8732ddaf329e46546474400d26f84c0f1c";
import { ClientData } from "./clientdata";
import { Collaboration } from "./collaboration";
import { CollaboratorEvents } from "./collaboratorevents";
import { CollaboratorV2FormW9Info } from "./collaboratorv2formw9info";
import { MemberClientWireAccount } from "./memberclientwireaccount";
import { MemberData } from "./memberdata";
import { Ninecd48bf78a297540b0ec6f45365beb8d6ce0ee88e6d244115ad226e6701011a3 } from "./ninecd48bf78a297540b0ec6f45365beb8d6ce0ee88e6d244115ad226e6701011a3";
import { RedactedMember } from "./redactedmember";
import { UserRoles } from "./userroles";
import { Expose, Type } from "class-transformer";

export enum StatusCollaboratorV2 {
    Active = "Active",
    Inactive = "Inactive",
    Pending = "Pending",
}

export enum TaxStatusCollaboratorV2 {
    Complete = "Complete",
    Failed = "Failed",
    Pending = "Pending",
    Incomplete = "Incomplete",
}

export class CollaboratorV2 extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "achCreditAccount" })
    @Type(() => MemberClientWireAccount)
    achCreditAccount: MemberClientWireAccount;

    @SpeakeasyMetadata()
    @Expose({ name: "clientData" })
    @Type(() => ClientData)
    clientData?: ClientData;

    @SpeakeasyMetadata()
    @Expose({ name: "clientId" })
    clientId: string;

    @SpeakeasyMetadata({ elemType: Collaboration })
    @Expose({ name: "collaborations" })
    @Type(() => Collaboration)
    collaborations: Collaboration[];

    @SpeakeasyMetadata()
    @Expose({ name: "createdAt" })
    createdAt: string;

    @SpeakeasyMetadata()
    @Expose({ name: "firstCollaborationId" })
    firstCollaborationId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "form1099Balances" })
    @Type(() => B9789f45f8c8070ff38a64d80c2e4a8732ddaf329e46546474400d26f84c0f1c)
    form1099Balances: B9789f45f8c8070ff38a64d80c2e4a8732ddaf329e46546474400d26f84c0f1c;

    @SpeakeasyMetadata()
    @Expose({ name: "formW9Data" })
    @Type(() => CollaboratorV2FormW9Info)
    formW9Data: CollaboratorV2FormW9Info;

    @SpeakeasyMetadata()
    @Expose({ name: "internal" })
    @Type(() => Ninecd48bf78a297540b0ec6f45365beb8d6ce0ee88e6d244115ad226e6701011a3)
    internal: Ninecd48bf78a297540b0ec6f45365beb8d6ce0ee88e6d244115ad226e6701011a3;

    @SpeakeasyMetadata()
    @Expose({ name: "internationalWireAccount" })
    @Type(() => MemberClientWireAccount)
    internationalWireAccount: MemberClientWireAccount;

    @SpeakeasyMetadata()
    @Expose({ name: "labels" })
    labels: Record<string, string>;

    @SpeakeasyMetadata()
    @Expose({ name: "member" })
    @Type(() => RedactedMember)
    member: RedactedMember;

    @SpeakeasyMetadata()
    @Expose({ name: "memberData" })
    @Type(() => MemberData)
    memberData?: MemberData;

    @SpeakeasyMetadata()
    @Expose({ name: "memberEvents" })
    @Type(() => CollaboratorEvents)
    memberEvents?: CollaboratorEvents;

    @SpeakeasyMetadata()
    @Expose({ name: "memberId" })
    memberId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "primaryCollaborationId" })
    primaryCollaborationId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: StatusCollaboratorV2;

    @SpeakeasyMetadata()
    @Expose({ name: "taxStatus" })
    taxStatus: TaxStatusCollaboratorV2;

    @SpeakeasyMetadata()
    @Expose({ name: "updatedAt" })
    updatedAt: string;

    @SpeakeasyMetadata()
    @Expose({ name: "userRoles" })
    @Type(() => UserRoles)
    userRoles: UserRoles;
}
