/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum StatusCollaboratorCreateRequest {
    Active = "Active",
    Inactive = "Inactive",
    Pending = "Pending",
    LessThanNilGreaterThan = "<nil>",
}

export class CollaboratorCreateRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "clientData" })
    clientData?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "clientId" })
    clientId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "collaboratorGroupId" })
    collaboratorGroupId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "formW9Data" })
    formW9Data?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "integration" })
    integration?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "labels" })
    labels?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "memberCompany" })
    memberCompany?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "memberEmail" })
    memberEmail?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "memberId" })
    memberId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "memberName" })
    memberName?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: StatusCollaboratorCreateRequest;
}
