/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase } from "../../../internal/utils";

/**
 * A file stream for a W9 PDF download.
 */
export class DownloadW9Response extends SpeakeasyBase {}
