/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class ExternalIdsQuickbooksData extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "doCreate" })
    doCreate?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "doDelete" })
    doDelete?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "doUpdate" })
    doUpdate?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    @SpeakeasyMetadata()
    @Expose({ name: "syncToken" })
    syncToken: string;
}
