/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Address } from "./address";
import { ClientOptions } from "./clientoptions";
import { ExternalIds } from "./externalids";
import { InvoiceEvents } from "./invoiceevents";
import { InvoiceLineItem } from "./invoicelineitem";
import { MemberOptions } from "./memberoptions";
import { UserRoles } from "./userroles";
import { Expose, Type } from "class-transformer";

export enum InvoiceAcceptedPaymentMethods {
    Credit = "Credit",
    Ach = "ACH",
    Manual = "Manual",
    LessThanNilGreaterThan = "<nil>",
}

export enum CurrencyInvoice {
    Usd = "USD",
    Cad = "CAD",
}

export enum StatusInvoice {
    Draft = "Draft",
    Open = "Open",
    Overdue = "Overdue",
    Cancelled = "Cancelled",
    Pending = "Pending",
    PaymentInTransit = "PaymentInTransit",
    Paid = "Paid",
}

/**
 * An invoice
 */
export class Invoice extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "acceptedPaymentMethods" })
    acceptedPaymentMethods?: InvoiceAcceptedPaymentMethods[];

    @SpeakeasyMetadata()
    @Expose({ name: "accountId" })
    accountId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    amount: number;

    @SpeakeasyMetadata()
    @Expose({ name: "amountDetails" })
    amountDetails?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "attachments" })
    attachments?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "bankTransferInfo" })
    bankTransferInfo?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "chargedFees" })
    chargedFees?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "client" })
    @Type(() => ClientOptions)
    client: ClientOptions;

    @SpeakeasyMetadata()
    @Expose({ name: "clientId" })
    clientId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "collaborators" })
    collaborators?: any[];

    @SpeakeasyMetadata()
    @Expose({ name: "createdAt" })
    createdAt: string;

    @SpeakeasyMetadata()
    @Expose({ name: "creditFeeHandling" })
    creditFeeHandling?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "currency" })
    currency: CurrencyInvoice;

    @SpeakeasyMetadata()
    @Expose({ name: "deductions" })
    deductions?: any[];

    @SpeakeasyMetadata()
    @Expose({ name: "dueDate" })
    dueDate: string;

    @SpeakeasyMetadata()
    @Expose({ name: "events" })
    @Type(() => InvoiceEvents)
    events: InvoiceEvents;

    @SpeakeasyMetadata()
    @Expose({ name: "externalIds" })
    @Type(() => ExternalIds)
    externalIds: ExternalIds;

    @SpeakeasyMetadata()
    @Expose({ name: "integration" })
    integration?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "internationalBankTransferInfo" })
    internationalBankTransferInfo?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "invoiceId" })
    invoiceId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "invoiceNotes" })
    invoiceNotes?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "invoiceNumber" })
    invoiceNumber: string;

    @SpeakeasyMetadata()
    @Expose({ name: "invoiceTemplateId" })
    invoiceTemplateId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "labels" })
    labels: Record<string, string>;

    @SpeakeasyMetadata()
    @Expose({ name: "lateFeeHandling" })
    lateFeeHandling?: any;

    @SpeakeasyMetadata({ elemType: InvoiceLineItem })
    @Expose({ name: "lineItems" })
    @Type(() => InvoiceLineItem)
    lineItems: InvoiceLineItem[];

    @SpeakeasyMetadata()
    @Expose({ name: "member" })
    @Type(() => MemberOptions)
    member: MemberOptions;

    @SpeakeasyMetadata()
    @Expose({ name: "memberAddress" })
    @Type(() => Address)
    memberAddress: Address;

    @SpeakeasyMetadata()
    @Expose({ name: "memberClientId" })
    memberClientId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "memberFormattedAddressLines" })
    memberFormattedAddressLines?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "memberId" })
    memberId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    metadata?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "notificationPreferences" })
    notificationPreferences?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "parentInvoiceId" })
    parentInvoiceId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "paymentInfo" })
    paymentInfo?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "paymentMethodId" })
    paymentMethodId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "payoutDestinations" })
    payoutDestinations?: any[];

    @SpeakeasyMetadata()
    @Expose({ name: "processingFees" })
    processingFees?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "sourceId" })
    sourceId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: StatusInvoice;

    @SpeakeasyMetadata()
    @Expose({ name: "updatedAt" })
    updatedAt: string;

    @SpeakeasyMetadata()
    @Expose({ name: "userRoles" })
    @Type(() => UserRoles)
    userRoles: UserRoles;

    @SpeakeasyMetadata()
    @Expose({ name: "withholdings" })
    withholdings?: any;
}
