/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum CurrencyInvoiceCollaborator {
    Usd = "USD",
    Cad = "CAD",
}

export class InvoiceCollaborator extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    amount: number;

    @SpeakeasyMetadata()
    @Expose({ name: "currency" })
    currency: CurrencyInvoiceCollaborator;

    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description: string;

    @SpeakeasyMetadata()
    @Expose({ name: "invoiceId" })
    invoiceId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "memberClientId" })
    memberClientId: string;
}
