/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum StatusInvoiceTemplateUpdateRequest {
    Active = "Active",
    Draft = "Draft",
    Expired = "Expired",
    Cancelled = "Cancelled",
    LessThanNilGreaterThan = "<nil>",
}

export class InvoiceTemplateUpdateRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "accountId" })
    accountId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "autoPaymentRequired" })
    autoPaymentRequired?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "dueInDays" })
    dueInDays?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "frequency" })
    frequency?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "invoiceData" })
    invoiceData?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "isSchedulingOnly" })
    isSchedulingOnly?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "labels" })
    labels?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "paymentMethodId" })
    paymentMethodId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "scheduleDates" })
    scheduleDates?: any[];

    @SpeakeasyMetadata()
    @Expose({ name: "sendEmails" })
    sendEmails?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: StatusInvoiceTemplateUpdateRequest;
}
