/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class InvoiceAttachments extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "customAttachmentIds" })
    customAttachmentIds?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "customAttachmentInfo" })
    customAttachmentInfo?: any[];

    @SpeakeasyMetadata()
    @Expose({ name: "invoiceLink" })
    invoiceLink?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "invoicePdf" })
    invoicePdf?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "receiptPdf" })
    receiptPdf?: string;
}
