/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum InvoiceUpdateRequestAcceptedPaymentMethods {
    Credit = "Credit",
    Ach = "ACH",
    Manual = "Manual",
    LessThanNilGreaterThan = "<nil>",
}

export class InvoiceUpdateRequestClient2 extends SpeakeasyBase {}

export class InvoiceUpdateRequestMember2 extends SpeakeasyBase {}

export enum StatusInvoiceUpdateRequest {
    Draft = "Draft",
    Open = "Open",
    Overdue = "Overdue",
    Cancelled = "Cancelled",
    Pending = "Pending",
    PaymentInTransit = "PaymentInTransit",
    Paid = "Paid",
    LessThanNilGreaterThan = "<nil>",
}

export class InvoiceUpdateRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "acceptedPaymentMethods" })
    acceptedPaymentMethods?: InvoiceUpdateRequestAcceptedPaymentMethods[];

    @SpeakeasyMetadata()
    @Expose({ name: "attachments" })
    attachments?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "chargedFees" })
    chargedFees?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "client" })
    client?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "collaborators" })
    collaborators?: any[];

    @SpeakeasyMetadata()
    @Expose({ name: "creditFeeHandling" })
    creditFeeHandling?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "dueDate" })
    dueDate?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "integration" })
    integration?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "invoiceNotes" })
    invoiceNotes?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "labels" })
    labels?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "lateFeeHandling" })
    lateFeeHandling?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "lineItems" })
    lineItems?: any[];

    @SpeakeasyMetadata()
    @Expose({ name: "member" })
    member?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "memberClientId" })
    memberClientId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    metadata?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "notificationPreferences" })
    notificationPreferences?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: StatusInvoiceUpdateRequest;
}
