/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum MemberClientRequirementResponseRequirementType {
    Signature = "Signature",
}

export enum StatusMemberClientRequirementResponse {
    New = "New",
    Sent = "Sent",
    Pending = "Pending",
    Complete = "Complete",
    LessThanNilGreaterThan = "<nil>",
}

export class MemberClientRequirementResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "clientId" })
    clientId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "collaboratorGroupId" })
    collaboratorGroupId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "document" })
    document?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "documentId" })
    documentId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "eligibilityRequirementId" })
    eligibilityRequirementId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "requirementType" })
    requirementType: MemberClientRequirementResponseRequirementType;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: StatusMemberClientRequirementResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "templateId" })
    templateId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "validFor" })
    validFor?: number;
}
