/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum DeliveryMethodMemberClientForm1099Balances {
    Electronic = "Electronic",
    Mail = "Mail",
}

export enum ExclusionReasonMemberClientForm1099Balances {
    BelowThreshold = "BelowThreshold",
    CompanyStructure = "CompanyStructure",
    NonUsEntity = "NonUsEntity",
}

export enum StatusMemberClientForm1099Balances {
    Ready = "Ready",
    NeedsActionInfo = "NeedsActionInfo",
    NeedsActionDispute = "NeedsActionDispute",
    Submitted = "Submitted",
    Rejected = "Rejected",
    Accepted = "Accepted",
    Excluded = "Excluded",
}

export class MemberClientForm1099BalancesTaxForm2 extends SpeakeasyBase {}

export enum TypeMemberClientForm1099Balances {
    Nec = "NEC",
}

export class MemberClientForm1099Balances extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "adjustments" })
    adjustments: number;

    @SpeakeasyMetadata()
    @Expose({ name: "correction" })
    correction?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "deliveryMethod" })
    deliveryMethod: DeliveryMethodMemberClientForm1099Balances;

    @SpeakeasyMetadata()
    @Expose({ name: "dispute" })
    dispute?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "events" })
    events?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "exclusionReason" })
    exclusionReason: ExclusionReasonMemberClientForm1099Balances;

    @SpeakeasyMetadata()
    @Expose({ name: "form1099Generated" })
    form1099Generated: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "paymentProcessingFees" })
    paymentProcessingFees: number;

    @SpeakeasyMetadata()
    @Expose({ name: "platformIncome" })
    platformIncome: number;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: StatusMemberClientForm1099Balances;

    @SpeakeasyMetadata()
    @Expose({ name: "taxForm" })
    taxForm?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "taxFormId" })
    taxFormId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type: TypeMemberClientForm1099Balances;
}
