/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class Ninetyf96495b02c2509fff131505484d46479a91b7d23ed2b0f438ca117d0bccad7 extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "2021" })
    twoThousandAndTwentyOne?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "2022" })
    twoThousandAndTwentyTwo?: any;
}
