/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { FeeHandlingConfig } from "./feehandlingconfig";
import { InvoiceLineItemsCreateRequest } from "./invoicelineitemscreaterequest";
import { Expose, Type } from "class-transformer";

export enum PayableCreateRequestAcceptedPaymentMethods {
    Credit = "Credit",
    Ach = "ACH",
    Manual = "Manual",
    LessThanNilGreaterThan = "<nil>",
}

export class PayableCreateRequestClient2 extends SpeakeasyBase {}

export enum CurrencyPayableCreateRequest {
    Usd = "USD",
    Cad = "CAD",
    LessThanNilGreaterThan = "<nil>",
}

export class PayableCreateRequestMember2 extends SpeakeasyBase {}

export enum StatusPayableCreateRequest {
    Draft = "Draft",
    Open = "Open",
    Overdue = "Overdue",
    Cancelled = "Cancelled",
    Pending = "Pending",
    PaymentInTransit = "PaymentInTransit",
    Paid = "Paid",
    LessThanNilGreaterThan = "<nil>",
}

export class PayableCreateRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "acceptedPaymentMethods" })
    acceptedPaymentMethods?: PayableCreateRequestAcceptedPaymentMethods[];

    @SpeakeasyMetadata()
    @Expose({ name: "attachments" })
    attachments?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "client" })
    client?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "collaboratorId" })
    collaboratorId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "creditFeeHandling" })
    @Type(() => FeeHandlingConfig)
    creditFeeHandling: FeeHandlingConfig;

    @SpeakeasyMetadata()
    @Expose({ name: "currency" })
    currency?: CurrencyPayableCreateRequest;

    @SpeakeasyMetadata()
    @Expose({ name: "dueDate" })
    dueDate: string;

    @SpeakeasyMetadata()
    @Expose({ name: "integration" })
    integration?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "invoiceNotes" })
    invoiceNotes?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "labels" })
    labels?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "lateFeeHandling" })
    lateFeeHandling?: any;

    @SpeakeasyMetadata({ elemType: InvoiceLineItemsCreateRequest })
    @Expose({ name: "lineItems" })
    @Type(() => InvoiceLineItemsCreateRequest)
    lineItems: InvoiceLineItemsCreateRequest[];

    @SpeakeasyMetadata()
    @Expose({ name: "member" })
    member?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "memberClientId" })
    memberClientId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    metadata?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "notificationPreferences" })
    notificationPreferences?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: StatusPayableCreateRequest;
}
