/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class CreateAdditionalDataResponse extends SpeakeasyBase {
    /**
     * Custom fields that are set on memberClient object to describe collaborator-member
     */
    @SpeakeasyMetadata()
    additionalData?: shared.AdditionalData;

    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
