/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class CreateBulkCalculation1099BatchItemRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    bulkCalculation1099ItemCreate?: shared.BulkCalculation1099ItemCreate;

    /**
     * Unique identifier for a batch
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=batchId" })
    batchId: string;
}

export class CreateBulkCalculation1099BatchItemResponse extends SpeakeasyBase {
    /**
     * An item that will be converted into a calculation 1099
     */
    @SpeakeasyMetadata()
    bulkCalculation1099Item?: shared.BulkCalculation1099Item;

    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
