/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class CreateClientInvoiceTemplateResponse extends SpeakeasyBase {
    /**
     * A client created invoiceTemplate (recurring Invoice)
     */
    @SpeakeasyMetadata()
    clientInvoiceTemplate?: shared.ClientInvoiceTemplate;

    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
