/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class DeleteCollaboratorGroupEligibilityRequirementRequest extends SpeakeasyBase {
    /**
     * Unique eligibility Requirement Id
     */
    @SpeakeasyMetadata({
        data: "pathParam, style=simple;explode=false;name=eligibilityRequirementId",
    })
    eligibilityRequirementId: string;

    /**
     * Unique identifier
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=id" })
    id: string;
}

export class DeleteCollaboratorGroupEligibilityRequirementResponse extends SpeakeasyBase {
    /**
     * Collaborator Configuration Per Group
     */
    @SpeakeasyMetadata()
    collaboratorGroupResponse?: shared.CollaboratorGroupResponse;

    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
