/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetCollaboratorV2Request extends SpeakeasyBase {
    /**
     * Unique identifier of a member
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=memberId" })
    memberId: string;
}

export class GetCollaboratorV2Response extends SpeakeasyBase {
    /**
     * A single V2 Collaborator
     */
    @SpeakeasyMetadata()
    collaboratorV2?: shared.CollaboratorV2;

    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
