/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetCollaboratorsDetailsV2Response extends SpeakeasyBase {
    /**
     * Collaborators list in the report
     */
    @SpeakeasyMetadata({ elemType: shared.CollaboratorsReportResponse })
    collaboratorsReportResponses?: shared.CollaboratorsReportResponse[];

    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
