/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class ListBulkInvoiceBatchItemsRequest extends SpeakeasyBase {
    /**
     * Unique identifier for a batch
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=batchId" })
    batchId: string;
}

export class ListBulkInvoiceBatchItemsResponse extends SpeakeasyBase {
    /**
     * A list of bulk invoice items
     */
    @SpeakeasyMetadata({ elemType: shared.BulkInvoiceItem })
    bulkInvoiceItems?: shared.BulkInvoiceItem[];

    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
