/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class ListCollaboratorGroupsResponse extends SpeakeasyBase {
    /**
     * A list of Collaborator Configurations created by client
     */
    @SpeakeasyMetadata({ elemType: shared.CollaboratorGroupResponse })
    collaboratorGroupResponses?: shared.CollaboratorGroupResponse[];

    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
