/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class ListCollaboratorsResponse extends SpeakeasyBase {
    /**
     *  A list of collaborators
     */
    @SpeakeasyMetadata({ elemType: shared.CollaboratorSchema })
    collaboratorSchemas?: shared.CollaboratorSchema[];

    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
