/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class ListBulkPayableBatchesResponse extends SpeakeasyBase {
    /**
     * A list of bulk payable batches
     */
    @SpeakeasyMetadata({ elemType: shared.BulkPayableBatch })
    bulkPayableBatches?: shared.BulkPayableBatch[];

    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
