/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class ListBulkClientBatchesResponse extends SpeakeasyBase {
    /**
     * A list of bulk client batches
     */
    @SpeakeasyMetadata({ elemType: shared.BulkClientBatch })
    bulkClientBatches?: shared.BulkClientBatch[];

    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
