/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class ListAdditionalSettingsResponse extends SpeakeasyBase {
    /**
     * A list of custom data-points
     */
    @SpeakeasyMetadata({ elemType: shared.AdditionalData })
    additionalData?: shared.AdditionalData[];

    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
