/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class UpdateAdditionalSettingsRequest extends SpeakeasyBase {
    /**
     * Unique identifier
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=id" })
    id: string;

    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    additionalDataUpdateRequest?: shared.AdditionalDataUpdateRequest;
}

export class UpdateAdditionalSettingsResponse extends SpeakeasyBase {
    /**
     * Custom fields that are set on memberClient object to describe collaborator-member
     */
    @SpeakeasyMetadata()
    additionalData?: shared.AdditionalData;

    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
