/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class UpdateBulkPayableBatchItemRequest extends SpeakeasyBase {
    /**
     * Unique identifier for a batch
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=batchId" })
    batchId: string;

    /**
     * Unique identifier for an item in a batch
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=batchItemId" })
    batchItemId: string;

    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    bulkPayableItemUpdate?: shared.BulkPayableItemUpdate;
}

export class UpdateBulkPayableBatchItemResponse extends SpeakeasyBase {
    /**
     * An item that will be converted into a payable
     */
    @SpeakeasyMetadata()
    bulkPayableItem?: shared.BulkPayableItem;

    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
